# see https://github.com/Homebrew/homebrew-bundle
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "antigen"
brew "shellcheck"
brew "zsh"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
